# Theme Settings
minimal_mistakes_skin: "default" # Change this to any skin you prefer

# Site Settings
locale: "en-US"
title: "James Winslow's Portfolio"
title_separator: "-"
subtitle: "Data Scientist"
name: "James Winslow"
description: "A Data Scientist with a passion for solving complex problems using data-driven approaches."
url: "https://james-winslow.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "james-winslow/James-Winslow.github.io" # GitHub username/repo-name
teaser: "/assets/images/teaser.png" # path of fallback teaser image
logo: "/assets/images/logo.png" # path of logo image to display in the masthead
masthead_title: "James Winslow" # overrides the website title displayed in the masthead
breadcrumbs: true # true, false (default)
words_per_minute: 200
enable_copy_code_button: true # true, false (default)
copyright: "James Winslow"
copyright_url: "https://james-winslow.github.io"

# Comments
comments:
  provider: false # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"

# Search
search: true
search_full_content: false
search_provider: "lunr" # lunr (default), algolia, google

# Analytics
analytics:
  provider: "google" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "UA-XXXXXXXX-X" # replace with your Google Analytics tracking ID
    anonymize_ip: true # true, false (default)

# Site Author
author:
  name: "James Winslow"
  avatar: "/assets/images/bio-photo.jpg" # path of avatar image
  bio: "I am a Data Scientist with a passion for solving complex problems using data-driven approaches."
  location: "City, Country"
  email: "email@example.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:email@example.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://james-winslow.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/username"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/username"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/username"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/username"

# Include and Exclude Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
# for configuration details
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins (previously gems)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
